spring:
  profiles:
    active: local

  application:
    name: acklet

  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB

  # Database configuration driver
  datasource:
    driver-class-name: org.postgresql.Driver

  # JPA & Hibernate base configuration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate # Use Flyway for migrations
    properties:
      hibernate:
        format_sql: false

  # Flyway configuration
  flyway:
    enabled: true
    baseline-on-migrate: true

# Base Logging settings
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%X{correlationId}] %-5level %logger{36} - %msg%n"

# SpringDoc OpenAPI configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: alpha
