// src/app/core/mock-data/categories.data.ts

import { Category } from '../models/category.model';

export const MOCK_CATEGORIES: Category[] = [
  {
    id: 'cat-1',
    name: 'Developer Tools',
    slug: 'developer-tools',
    description: 'Powerful utilities for developers — formatters, validators, encoders, and debuggers.',
    icon: 'code-2',
    color: '#6366f1',
    gradient: 'linear-gradient(135deg, #6366f1, #8b5cf6)',
    toolCount: 8,
    isFeatured: true,
  },
  {
    id: 'cat-2',
    name: 'AI Tools',
    slug: 'ai-tools',
    description: 'Leverage the power of AI for writing, analysis, optimization, and automation.',
    icon: 'brain',
    color: '#06b6d4',
    gradient: 'linear-gradient(135deg, #06b6d4, #0891b2)',
    toolCount: 4,
    isFeatured: true,
  },
  {
    id: 'cat-3',
    name: 'Business',
    slug: 'business',
    description: 'Tools to streamline workflows, reports, financial calculations, and business ops.',
    icon: 'briefcase',
    color: '#10b981',
    gradient: 'linear-gradient(135deg, #10b981, #059669)',
    toolCount: 3,
    isFeatured: true,
  },
  {
    id: 'cat-4',
    name: 'Productivity',
    slug: 'productivity',
    description: 'Boost your daily efficiency with smart text, time, and task management tools.',
    icon: 'zap',
    color: '#f59e0b',
    gradient: 'linear-gradient(135deg, #f59e0b, #d97706)',
    toolCount: 3,
    isFeatured: true,
  },
  {
    id: 'cat-5',
    name: 'Healthcare',
    slug: 'healthcare',
    description: 'Clinical-grade validators and utilities for healthcare data standards like FHIR and HL7.',
    icon: 'heart-pulse',
    color: '#ef4444',
    gradient: 'linear-gradient(135deg, #ef4444, #dc2626)',
    toolCount: 2,
    isFeatured: false,
  },
  {
    id: 'cat-6',
    name: 'Documents',
    slug: 'documents',
    description: 'Convert, compress, merge, and transform documents and office files effortlessly.',
    icon: 'file-text',
    color: '#8b5cf6',
    gradient: 'linear-gradient(135deg, #8b5cf6, #7c3aed)',
    toolCount: 2,
    isFeatured: false,
  },
  {
    id: 'cat-7',
    name: 'Validators',
    slug: 'validators',
    description: 'Validate JSON, YAML, HTML, URLs, emails, and more against industry schemas.',
    icon: 'shield-check',
    color: '#22c55e',
    gradient: 'linear-gradient(135deg, #22c55e, #16a34a)',
    toolCount: 3,
    isFeatured: false,
  },
  {
    id: 'cat-8',
    name: 'Generators',
    slug: 'generators',
    description: 'Generate UUIDs, passwords, QR codes, mock data, and more in seconds.',
    icon: 'sparkles',
    color: '#ec4899',
    gradient: 'linear-gradient(135deg, #ec4899, #db2777)',
    toolCount: 3,
    isFeatured: false,
  },
  {
    id: 'cat-9',
    name: 'Formatters',
    slug: 'formatters',
    description: 'Beautify and format JSON, SQL, HTML, CSS, and code for readability.',
    icon: 'align-left',
    color: '#f97316',
    gradient: 'linear-gradient(135deg, #f97316, #ea580c)',
    toolCount: 3,
    isFeatured: false,
  },
  {
    id: 'cat-10',
    name: 'Converters',
    slug: 'converters',
    description: 'Convert between units, formats, currencies, encodings, and data types.',
    icon: 'arrow-right-left',
    color: '#14b8a6',
    gradient: 'linear-gradient(135deg, #14b8a6, #0d9488)',
    toolCount: 3,
    isFeatured: false,
  },
];
