// src/app/core/mock-data/tools.data.ts

import { Tool } from '../models/tool.model';

export const MOCK_TOOLS: Tool[] = [
  // ── Developer Tools ────────────────────────────────────────
  {
    id: 'tool-1',
    name: 'JWT Inspector',
    slug: 'jwt-inspector',
    categoryId: 'cat-1',
    categoryName: 'Developer Tools',
    categoryIcon: 'code-2',
    shortDescription: 'Decode, verify, and inspect JSON Web Tokens in real-time.',
    description: 'JWT Inspector is a powerful browser-based tool that lets you decode and inspect JSON Web Tokens instantly. Paste any JWT and instantly see its header, payload, and signature components. Verify tokens against secrets, check expiry, and validate claims — all without sending your token to any server.',
    tags: ['JWT', 'Auth', 'Security', 'Token', 'Decode'],
    features: [
      'Real-time JWT decoding with syntax highlighting',
      'Header, payload, and signature breakdown',
      'Token expiry detection and time remaining',
      'Base64 encoded/decoded view toggle',
      'Claim validation and structure analysis',
      'Dark mode friendly output',
    ],
    usageSteps: [
      { step: 1, title: 'Paste your JWT', description: 'Copy your JSON Web Token and paste it into the input field.' },
      { step: 2, title: 'Instant Decode', description: 'The tool immediately decodes and formats all three parts of the token.' },
      { step: 3, title: 'Inspect Claims', description: 'Review the header algorithm, payload claims, and expiry information.' },
    ],
    screenshots: [
      { id: 'ss-1', title: 'Decoder View', description: 'The main JWT decoding interface' },
      { id: 'ss-2', title: 'Claims Table', description: 'Structured view of all JWT claims' },
    ],
    faqs: [
      { question: 'Is my JWT sent to any server?', answer: 'No. All decoding happens entirely in your browser using JavaScript. Your token never leaves your device.' },
      { question: 'Can I verify the signature?', answer: 'Yes. You can provide the secret key or public key to verify HMAC and RSA signatures.' },
    ],
    relatedToolIds: ['tool-4', 'tool-7', 'tool-2'],
    rating: 4.9,
    reviewCount: 1248,
    usageCount: 452000,
    isNew: false,
    isFeatured: true,
    isTrending: true,
    isPopular: true,
    icon: 'key-round',
    color: '#6366f1',
    gradient: 'linear-gradient(135deg, #6366f1, #8b5cf6)',
    addedDate: '2025-11-01',
  },
  {
    id: 'tool-2',
    name: 'JSON Formatter',
    slug: 'json-formatter',
    categoryId: 'cat-9',
    categoryName: 'Formatters',
    categoryIcon: 'align-left',
    shortDescription: 'Beautify, minify, and validate JSON with syntax highlighting.',
    description: 'JSON Formatter is the fastest way to clean up messy JSON. Paste your raw JSON to instantly beautify it with proper indentation and syntax highlighting. Minify for production, validate structure, and spot errors with clear line-level indicators.',
    tags: ['JSON', 'Format', 'Beautify', 'Minify', 'Validate'],
    features: [
      'One-click JSON beautification with configurable indent',
      'Minify JSON for production use',
      'Real-time syntax validation with error indicators',
      'Syntax-highlighted output',
      'Copy to clipboard with one click',
      'JSON path explorer',
    ],
    usageSteps: [
      { step: 1, title: 'Paste JSON', description: 'Paste your raw or malformed JSON into the input area.' },
      { step: 2, title: 'Format or Minify', description: 'Click Format to beautify or Minify to compress.' },
      { step: 3, title: 'Copy Result', description: 'Copy the output to clipboard with one click.' },
    ],
    screenshots: [
      { id: 'ss-1', title: 'Formatter View', description: 'Split-pane formatter with syntax highlighting' },
    ],
    faqs: [
      { question: 'What indent size does it use?', answer: 'Default is 2 spaces, but you can configure 2, 4 spaces, or tabs.' },
      { question: 'Can it handle large JSON files?', answer: 'Yes, the formatter handles JSON up to 10MB without performance issues.' },
    ],
    relatedToolIds: ['tool-1', 'tool-5', 'tool-15'],
    rating: 4.8,
    reviewCount: 2156,
    usageCount: 891000,
    isNew: false,
    isFeatured: true,
    isTrending: false,
    isPopular: true,
    icon: 'braces',
    color: '#f97316',
    gradient: 'linear-gradient(135deg, #f97316, #ea580c)',
    addedDate: '2025-10-15',
  },
  {
    id: 'tool-3',
    name: 'SQL Formatter',
    slug: 'sql-formatter',
    categoryId: 'cat-9',
    categoryName: 'Formatters',
    categoryIcon: 'align-left',
    shortDescription: 'Format and beautify SQL queries for MySQL, PostgreSQL, and more.',
    description: 'Transform messy SQL into clean, readable queries with proper keyword casing, indentation, and alignment. Supports MySQL, PostgreSQL, SQLite, and Microsoft SQL Server dialects.',
    tags: ['SQL', 'Database', 'Format', 'Query', 'MySQL', 'PostgreSQL'],
    features: [
      'Supports MySQL, PostgreSQL, SQLite, MSSQL dialects',
      'Keyword uppercase/lowercase normalization',
      'Indent-based clause alignment',
      'Inline comment preservation',
      'Copy formatted SQL instantly',
      'Dark and light syntax themes',
    ],
    usageSteps: [
      { step: 1, title: 'Paste your SQL', description: 'Paste raw or compressed SQL query into the editor.' },
      { step: 2, title: 'Select dialect', description: 'Choose your SQL dialect from the dropdown.' },
      { step: 3, title: 'Format & copy', description: 'Click format and copy the result.' },
    ],
    screenshots: [{ id: 'ss-1', title: 'SQL Editor', description: 'Multi-dialect SQL formatter with line numbers' }],
    faqs: [
      { question: 'Does it support stored procedures?', answer: 'Yes, complex stored procedures and CTEs are fully supported.' },
    ],
    relatedToolIds: ['tool-2', 'tool-5'],
    rating: 4.7,
    reviewCount: 983,
    usageCount: 320000,
    isNew: false,
    isFeatured: false,
    isTrending: true,
    isPopular: true,
    icon: 'database',
    color: '#10b981',
    gradient: 'linear-gradient(135deg, #10b981, #059669)',
    addedDate: '2025-11-20',
  },
  // ── AI Tools ───────────────────────────────────────────────
  {
    id: 'tool-4',
    name: 'Resume Analyzer',
    slug: 'resume-analyzer',
    categoryId: 'cat-2',
    categoryName: 'AI Tools',
    categoryIcon: 'brain',
    shortDescription: 'AI-powered resume analysis with ATS scoring and actionable insights.',
    description: 'Upload your resume and get an instant AI-powered analysis. Receive an ATS compatibility score, keyword gap analysis against a target job description, formatting feedback, and specific improvement suggestions to maximize interview rates.',
    tags: ['Resume', 'AI', 'ATS', 'Career', 'Job Search'],
    features: [
      'ATS compatibility score (0-100)',
      'Keyword gap analysis vs job descriptions',
      'Section-by-section feedback',
      'Action verb strength analysis',
      'Quantification opportunity detection',
      'Industry-specific keyword suggestions',
    ],
    usageSteps: [
      { step: 1, title: 'Upload Resume', description: 'Upload your resume as PDF or paste the text content.' },
      { step: 2, title: 'Add Job Description', description: 'Optionally paste the target job description for tailored analysis.' },
      { step: 3, title: 'Get Report', description: 'Receive your full AI-powered analysis report instantly.' },
    ],
    screenshots: [{ id: 'ss-1', title: 'Analysis Report', description: 'Detailed ATS scoring dashboard' }],
    faqs: [
      { question: 'Is my resume data private?', answer: 'Yes. Your resume is processed client-side and never stored on our servers.' },
      { question: 'What resume formats are supported?', answer: 'PDF, DOCX, and plain text formats are all supported.' },
    ],
    relatedToolIds: ['tool-5', 'tool-10'],
    rating: 4.9,
    reviewCount: 1872,
    usageCount: 280000,
    isNew: false,
    isFeatured: true,
    isTrending: true,
    isPopular: true,
    icon: 'file-search',
    color: '#06b6d4',
    gradient: 'linear-gradient(135deg, #06b6d4, #0891b2)',
    addedDate: '2025-12-01',
  },
  {
    id: 'tool-5',
    name: 'Prompt Optimizer',
    slug: 'prompt-optimizer',
    categoryId: 'cat-2',
    categoryName: 'AI Tools',
    categoryIcon: 'brain',
    shortDescription: 'Craft, refine, and optimize AI prompts for GPT, Claude, and Gemini.',
    description: 'Stop getting mediocre AI outputs. Prompt Optimizer analyzes your prompts and rewrites them using proven prompting frameworks like Chain-of-Thought, RLHF alignment, and role conditioning. Specifically optimized for GPT-4, Claude 3, and Gemini Pro.',
    tags: ['AI', 'Prompt', 'GPT', 'Claude', 'LLM', 'Optimization'],
    features: [
      'Multi-model optimization (GPT, Claude, Gemini)',
      'Chain-of-thought prompt enhancement',
      'Role and persona conditioning',
      'Output format specification helpers',
      'Prompt scoring and quality metrics',
      'Before/after comparison view',
    ],
    usageSteps: [
      { step: 1, title: 'Write your prompt', description: 'Enter your initial prompt idea or draft.' },
      { step: 2, title: 'Select target model', description: 'Choose which AI model you are targeting.' },
      { step: 3, title: 'Optimize', description: 'Get an enhanced prompt with framework annotations.' },
    ],
    screenshots: [{ id: 'ss-1', title: 'Optimizer View', description: 'Side-by-side prompt comparison interface' }],
    faqs: [
      { question: 'Does it work for all AI models?', answer: 'Optimized presets exist for GPT-4, Claude 3, and Gemini Pro, with a generic mode for others.' },
    ],
    relatedToolIds: ['tool-4'],
    rating: 4.8,
    reviewCount: 1100,
    usageCount: 195000,
    isNew: true,
    isFeatured: true,
    isTrending: true,
    isPopular: false,
    icon: 'wand-2',
    color: '#8b5cf6',
    gradient: 'linear-gradient(135deg, #8b5cf6, #7c3aed)',
    addedDate: '2026-01-15',
  },
  // ── Healthcare ─────────────────────────────────────────────
  {
    id: 'tool-6',
    name: 'FHIR Validator',
    slug: 'fhir-validator',
    categoryId: 'cat-5',
    categoryName: 'Healthcare',
    categoryIcon: 'heart-pulse',
    shortDescription: 'Validate FHIR R4 resources against official HL7 schemas instantly.',
    description: 'The FHIR Validator provides clinical-grade validation of HL7 FHIR R4 resources. Validate Patient, Observation, Condition, Medication, and other resource types against official schemas. Get detailed validation reports with specific error paths and correction suggestions.',
    tags: ['FHIR', 'HL7', 'Healthcare', 'Validate', 'R4', 'Clinical'],
    features: [
      'FHIR R4 full resource validation',
      'Supports 30+ resource types',
      'Detailed error path reporting (FHIRPath)',
      'Warning vs error level distinctions',
      'Profile conformance checking',
      'JSON and XML FHIR format support',
    ],
    usageSteps: [
      { step: 1, title: 'Paste FHIR Resource', description: 'Paste your FHIR R4 JSON or XML resource.' },
      { step: 2, title: 'Select Resource Type', description: 'Optionally specify the resource type for stricter validation.' },
      { step: 3, title: 'View Report', description: 'Get a detailed validation report with error locations.' },
    ],
    screenshots: [{ id: 'ss-1', title: 'Validation Report', description: 'Detailed FHIR validation results with FHIRPath errors' }],
    faqs: [
      { question: 'Is FHIR R5 supported?', answer: 'R4 is fully supported. R5 support is on the roadmap for Q3 2026.' },
      { question: 'Can I validate custom profiles?', answer: 'Custom StructureDefinition profiles can be uploaded for conformance checking.' },
    ],
    relatedToolIds: ['tool-7', 'tool-15'],
    rating: 4.7,
    reviewCount: 342,
    usageCount: 48000,
    isNew: false,
    isFeatured: false,
    isTrending: false,
    isPopular: false,
    icon: 'heart-pulse',
    color: '#ef4444',
    gradient: 'linear-gradient(135deg, #ef4444, #dc2626)',
    addedDate: '2025-12-10',
  },
  // ── Developer Tools (more) ─────────────────────────────────
  {
    id: 'tool-7',
    name: 'Base64 Encoder/Decoder',
    slug: 'base64-encoder',
    categoryId: 'cat-1',
    categoryName: 'Developer Tools',
    categoryIcon: 'code-2',
    shortDescription: 'Encode and decode Base64 strings, URLs, and files instantly.',
    description: 'Encode or decode any text, URL, or binary data to/from Base64 with support for URL-safe encoding variants. Works entirely in your browser — fast, private, and reliable.',
    tags: ['Base64', 'Encode', 'Decode', 'Binary', 'URL'],
    features: ['Standard and URL-safe Base64', 'UTF-8 and binary file encoding', 'Decode to readable text or hex', 'File upload support up to 10MB'],
    usageSteps: [
      { step: 1, title: 'Input', description: 'Type or paste text, or upload a file.' },
      { step: 2, title: 'Encode/Decode', description: 'Choose direction and click convert.' },
      { step: 3, title: 'Copy', description: 'Copy the result to clipboard.' },
    ],
    screenshots: [{ id: 'ss-1', title: 'Encoder View', description: 'Base64 encoding interface' }],
    faqs: [{ question: 'Is URL-safe Base64 supported?', answer: 'Yes, both standard (+/) and URL-safe (-_) variants are supported.' }],
    relatedToolIds: ['tool-1', 'tool-2'],
    rating: 4.7,
    reviewCount: 876,
    usageCount: 340000,
    isNew: false,
    isFeatured: false,
    isTrending: false,
    isPopular: true,
    icon: 'binary',
    color: '#6366f1',
    gradient: 'linear-gradient(135deg, #6366f1, #8b5cf6)',
    addedDate: '2025-10-20',
  },
  {
    id: 'tool-8',
    name: 'Regex Tester',
    slug: 'regex-tester',
    categoryId: 'cat-1',
    categoryName: 'Developer Tools',
    categoryIcon: 'code-2',
    shortDescription: 'Test, debug, and explain regular expressions with real-time match highlighting.',
    description: 'Build and debug regular expressions with an interactive live-preview editor. Matches are highlighted in real-time, capture groups are labeled, and a plain-English explanation of your regex is provided.',
    tags: ['Regex', 'RegExp', 'Pattern', 'Match', 'Debug'],
    features: ['Live match highlighting', 'Named capture groups', 'Plain-English regex explanation', 'Flag toggles (g, i, m, s)', 'Test against multiple strings'],
    usageSteps: [
      { step: 1, title: 'Enter Pattern', description: 'Type your regex pattern in the pattern field.' },
      { step: 2, title: 'Add Test Strings', description: 'Add strings to test the pattern against.' },
      { step: 3, title: 'See Matches', description: 'Matches and groups are highlighted in real-time.' },
    ],
    screenshots: [{ id: 'ss-1', title: 'Regex Editor', description: 'Live regex tester with match highlighting' }],
    faqs: [{ question: 'What regex flavor is used?', answer: 'JavaScript RegExp engine (ES2024) is used.' }],
    relatedToolIds: ['tool-1', 'tool-15'],
    rating: 4.8,
    reviewCount: 723,
    usageCount: 215000,
    isNew: false,
    isFeatured: false,
    isTrending: true,
    isPopular: true,
    icon: 'search-code',
    color: '#ec4899',
    gradient: 'linear-gradient(135deg, #ec4899, #db2777)',
    addedDate: '2025-11-05',
  },
  // ── Generators ─────────────────────────────────────────────
  {
    id: 'tool-9',
    name: 'UUID Generator',
    slug: 'uuid-generator',
    categoryId: 'cat-8',
    categoryName: 'Generators',
    categoryIcon: 'sparkles',
    shortDescription: 'Generate UUIDs v1, v4, and v7 — bulk generation with formatting options.',
    description: 'Generate cryptographically random UUIDs instantly. Supports UUID v1 (time-based), v4 (random), and v7 (sortable). Generate in bulk, with or without hyphens, and in uppercase or lowercase.',
    tags: ['UUID', 'GUID', 'Generate', 'Random', 'Unique'],
    features: ['UUID v1, v4, v7 support', 'Bulk generation (up to 1000)', 'Uppercase/lowercase output', 'Hyphen toggle', 'Copy all to clipboard'],
    usageSteps: [
      { step: 1, title: 'Select Version', description: 'Choose UUID v1, v4, or v7.' },
      { step: 2, title: 'Set Quantity', description: 'Select how many UUIDs to generate.' },
      { step: 3, title: 'Copy', description: 'Copy individual or all UUIDs.' },
    ],
    screenshots: [{ id: 'ss-1', title: 'UUID Generator', description: 'Bulk UUID generation panel' }],
    faqs: [{ question: 'Are UUIDs truly random?', answer: 'v4 UUIDs use crypto.getRandomValues() for cryptographic randomness.' }],
    relatedToolIds: ['tool-10', 'tool-7'],
    rating: 4.6,
    reviewCount: 445,
    usageCount: 178000,
    isNew: false,
    isFeatured: false,
    isTrending: false,
    isPopular: true,
    icon: 'fingerprint',
    color: '#ec4899',
    gradient: 'linear-gradient(135deg, #ec4899, #db2777)',
    addedDate: '2025-10-10',
  },
  {
    id: 'tool-10',
    name: 'Password Generator',
    slug: 'password-generator',
    categoryId: 'cat-8',
    categoryName: 'Generators',
    categoryIcon: 'sparkles',
    shortDescription: 'Generate strong, customizable passwords with entropy scoring.',
    description: 'Generate cryptographically secure passwords with full control over length, character sets, and exclusions. Real-time entropy calculation shows exactly how strong your password is.',
    tags: ['Password', 'Security', 'Generate', 'Entropy', 'Crypto'],
    features: ['Configurable length (8-128)', 'Uppercase, lowercase, digits, symbols', 'Exclude ambiguous characters', 'Entropy score display', 'Passphrase mode (word-based)', 'Bulk generation'],
    usageSteps: [
      { step: 1, title: 'Configure', description: 'Set length and allowed character types.' },
      { step: 2, title: 'Generate', description: 'Click generate for an instant secure password.' },
      { step: 3, title: 'Copy', description: 'Copy to clipboard securely.' },
    ],
    screenshots: [{ id: 'ss-1', title: 'Generator Panel', description: 'Password generator with strength meter' }],
    faqs: [{ question: 'Are passwords stored?', answer: 'No. All generation happens in your browser and nothing is stored.' }],
    relatedToolIds: ['tool-9', 'tool-1'],
    rating: 4.8,
    reviewCount: 932,
    usageCount: 421000,
    isNew: false,
    isFeatured: false,
    isTrending: false,
    isPopular: true,
    icon: 'lock-keyhole',
    color: '#22c55e',
    gradient: 'linear-gradient(135deg, #22c55e, #16a34a)',
    addedDate: '2025-10-08',
  },
  // ── Productivity ───────────────────────────────────────────
  {
    id: 'tool-11',
    name: 'Word Counter',
    slug: 'word-counter',
    categoryId: 'cat-4',
    categoryName: 'Productivity',
    categoryIcon: 'zap',
    shortDescription: 'Count words, characters, sentences, and reading time in real-time.',
    description: 'Instantly analyze any text block with live word, character, sentence, and paragraph counts. See reading time estimates, keyword density, and average word length — ideal for writers, bloggers, and content teams.',
    tags: ['Word Count', 'Text', 'Writing', 'Content', 'SEO'],
    features: ['Live word, character, and sentence count', 'Reading time estimate', 'Keyword density analysis', 'Unique word count', 'Paragraph counter', 'Speaking time estimate'],
    usageSteps: [
      { step: 1, title: 'Paste Text', description: 'Paste or type your text into the editor.' },
      { step: 2, title: 'See Stats', description: 'Stats update live as you type.' },
      { step: 3, title: 'Analyze', description: 'Drill into keyword density and readability.' },
    ],
    screenshots: [{ id: 'ss-1', title: 'Stats Panel', description: 'Real-time text analysis dashboard' }],
    faqs: [{ question: 'Does it support multiple languages?', answer: 'Yes, Unicode text in any language is fully supported.' }],
    relatedToolIds: ['tool-12', 'tool-5'],
    rating: 4.5,
    reviewCount: 612,
    usageCount: 98000,
    isNew: false,
    isFeatured: false,
    isTrending: false,
    isPopular: false,
    icon: 'type',
    color: '#f59e0b',
    gradient: 'linear-gradient(135deg, #f59e0b, #d97706)',
    addedDate: '2025-11-12',
  },
  {
    id: 'tool-12',
    name: 'Text Diff',
    slug: 'text-diff',
    categoryId: 'cat-4',
    categoryName: 'Productivity',
    categoryIcon: 'zap',
    shortDescription: 'Compare two text blocks and highlight differences line by line.',
    description: 'Text Diff provides a clean side-by-side or inline diff view between two text blocks. Ideal for comparing code, document revisions, configurations, and content edits.',
    tags: ['Diff', 'Compare', 'Text', 'Version', 'Review'],
    features: ['Side-by-side and inline diff modes', 'Line-level change highlighting', 'Character-level precision', 'Ignore whitespace option', 'Copy diff report'],
    usageSteps: [
      { step: 1, title: 'Input Texts', description: 'Paste the original and modified text into each panel.' },
      { step: 2, title: 'Compare', description: 'Click compare to see highlighted differences.' },
      { step: 3, title: 'Review', description: 'Switch between inline and side-by-side views.' },
    ],
    screenshots: [{ id: 'ss-1', title: 'Diff View', description: 'Side-by-side diff with color highlights' }],
    faqs: [{ question: 'Can I compare code files?', answer: 'Yes, paste any code or text for comparison.' }],
    relatedToolIds: ['tool-11', 'tool-2'],
    rating: 4.7,
    reviewCount: 489,
    usageCount: 76000,
    isNew: false,
    isFeatured: false,
    isTrending: false,
    isPopular: false,
    icon: 'git-compare',
    color: '#f59e0b',
    gradient: 'linear-gradient(135deg, #f59e0b, #d97706)',
    addedDate: '2025-12-05',
  },
  // ── Validators ─────────────────────────────────────────────
  {
    id: 'tool-13',
    name: 'YAML Validator',
    slug: 'yaml-validator',
    categoryId: 'cat-7',
    categoryName: 'Validators',
    categoryIcon: 'shield-check',
    shortDescription: 'Validate, lint, and format YAML configurations and documents.',
    description: 'Validate YAML syntax with line-precise error reporting. Perfect for Kubernetes configs, Docker Compose, CI/CD pipelines, and application settings. Supports YAML 1.1 and 1.2 specs.',
    tags: ['YAML', 'Validate', 'Lint', 'K8s', 'Config', 'Docker'],
    features: ['YAML 1.1 and 1.2 support', 'Line-level error indicators', 'Convert YAML to JSON', 'Multi-document YAML (---)', 'Schema validation (JSON Schema)'],
    usageSteps: [
      { step: 1, title: 'Paste YAML', description: 'Paste your YAML configuration.' },
      { step: 2, title: 'Validate', description: 'Errors are highlighted with line numbers.' },
      { step: 3, title: 'Fix & Convert', description: 'Optionally convert validated YAML to JSON.' },
    ],
    screenshots: [{ id: 'ss-1', title: 'YAML Editor', description: 'YAML validator with error annotations' }],
    faqs: [{ question: 'Is Kubernetes YAML supported?', answer: 'Yes, including multi-document YAML files with --- separators.' }],
    relatedToolIds: ['tool-2', 'tool-15'],
    rating: 4.6,
    reviewCount: 328,
    usageCount: 89000,
    isNew: false,
    isFeatured: false,
    isTrending: false,
    isPopular: false,
    icon: 'shield-check',
    color: '#22c55e',
    gradient: 'linear-gradient(135deg, #22c55e, #16a34a)',
    addedDate: '2025-11-25',
  },
  {
    id: 'tool-14',
    name: 'HTML Minifier',
    slug: 'html-minifier',
    categoryId: 'cat-9',
    categoryName: 'Formatters',
    categoryIcon: 'align-left',
    shortDescription: 'Minify HTML to reduce page size and improve load performance.',
    description: 'Strip whitespace, comments, and redundant attributes from HTML to create a lean production-ready version. Shows exact byte savings and percentage reduction.',
    tags: ['HTML', 'Minify', 'Compress', 'Web', 'Performance'],
    features: ['Remove whitespace and newlines', 'Strip HTML comments', 'Collapse inline CSS', 'Collapse inline JS', 'Byte savings report'],
    usageSteps: [
      { step: 1, title: 'Paste HTML', description: 'Paste your HTML markup.' },
      { step: 2, title: 'Configure', description: 'Select which optimizations to apply.' },
      { step: 3, title: 'Minify', description: 'Get minified HTML with byte savings stats.' },
    ],
    screenshots: [{ id: 'ss-1', title: 'Minifier View', description: 'HTML minifier with stats panel' }],
    faqs: [{ question: 'Will it break my HTML?', answer: 'Safe defaults preserve semantic structure. Advanced options can be toggled cautiously.' }],
    relatedToolIds: ['tool-2', 'tool-3'],
    rating: 4.5,
    reviewCount: 214,
    usageCount: 54000,
    isNew: false,
    isFeatured: false,
    isTrending: false,
    isPopular: false,
    icon: 'code',
    color: '#f97316',
    gradient: 'linear-gradient(135deg, #f97316, #ea580c)',
    addedDate: '2025-12-15',
  },
  {
    id: 'tool-15',
    name: 'CSV to JSON',
    slug: 'csv-to-json',
    categoryId: 'cat-10',
    categoryName: 'Converters',
    categoryIcon: 'arrow-right-left',
    shortDescription: 'Convert CSV data to well-structured JSON arrays instantly.',
    description: 'Transform CSV spreadsheet data into clean JSON arrays or objects. Auto-detects headers, handles quoted fields with commas, and lets you preview the output in real time.',
    tags: ['CSV', 'JSON', 'Convert', 'Data', 'Transform'],
    features: ['Auto header detection', 'Quoted field handling', 'Custom delimiter support (comma, semicolon, tab)', 'Live JSON preview', 'Download result as .json file'],
    usageSteps: [
      { step: 1, title: 'Paste CSV', description: 'Paste your CSV content or upload a .csv file.' },
      { step: 2, title: 'Configure', description: 'Set delimiter and header options.' },
      { step: 3, title: 'Convert', description: 'Preview and download the JSON output.' },
    ],
    screenshots: [{ id: 'ss-1', title: 'Converter View', description: 'CSV to JSON conversion with live preview' }],
    faqs: [{ question: 'Is nested JSON supported?', answer: 'Flat JSON arrays are generated. Use dot-notation headers for nested output.' }],
    relatedToolIds: ['tool-2', 'tool-16'],
    rating: 4.7,
    reviewCount: 567,
    usageCount: 143000,
    isNew: false,
    isFeatured: false,
    isTrending: true,
    isPopular: true,
    icon: 'table-2',
    color: '#14b8a6',
    gradient: 'linear-gradient(135deg, #14b8a6, #0d9488)',
    addedDate: '2025-11-18',
  },
  {
    id: 'tool-16',
    name: 'Unit Converter',
    slug: 'unit-converter',
    categoryId: 'cat-10',
    categoryName: 'Converters',
    categoryIcon: 'arrow-right-left',
    shortDescription: 'Convert between 200+ units across length, weight, temperature, and more.',
    description: 'A comprehensive unit conversion tool covering length, weight, temperature, area, volume, speed, data storage, energy, and pressure. Conversion happens instantly as you type.',
    tags: ['Units', 'Convert', 'Measurement', 'Length', 'Weight', 'Temperature'],
    features: ['200+ units across 10 categories', 'Live bidirectional conversion', 'Formula display', 'Scientific notation support', 'Metric and Imperial systems'],
    usageSteps: [
      { step: 1, title: 'Select Category', description: 'Choose the measurement category (e.g., Length).' },
      { step: 2, title: 'Enter Value', description: 'Type your value in any unit.' },
      { step: 3, title: 'See All Conversions', description: 'All equivalent values update instantly.' },
    ],
    screenshots: [{ id: 'ss-1', title: 'Converter', description: 'Unit conversion grid with live values' }],
    faqs: [{ question: 'Does it support currency?', answer: 'Currency is on the roadmap; current support is physical units only.' }],
    relatedToolIds: ['tool-15', 'tool-17'],
    rating: 4.6,
    reviewCount: 398,
    usageCount: 112000,
    isNew: false,
    isFeatured: false,
    isTrending: false,
    isPopular: true,
    icon: 'ruler',
    color: '#14b8a6',
    gradient: 'linear-gradient(135deg, #14b8a6, #0d9488)',
    addedDate: '2025-10-30',
  },
  {
    id: 'tool-17',
    name: 'Markdown Preview',
    slug: 'markdown-preview',
    categoryId: 'cat-1',
    categoryName: 'Developer Tools',
    categoryIcon: 'code-2',
    shortDescription: 'Write Markdown and preview rendered HTML side by side in real-time.',
    description: 'A live Markdown editor with real-time HTML preview. Supports GitHub Flavored Markdown including tables, task lists, fenced code blocks, and footnotes.',
    tags: ['Markdown', 'Preview', 'GFM', 'Documentation', 'Writing'],
    features: ['GitHub Flavored Markdown (GFM)', 'Real-time preview', 'Syntax highlighted code blocks', 'Table support', 'Task list checkboxes', 'Export as HTML'],
    usageSteps: [
      { step: 1, title: 'Write Markdown', description: 'Type your Markdown in the left editor.' },
      { step: 2, title: 'Preview', description: 'See rendered HTML on the right in real-time.' },
      { step: 3, title: 'Export', description: 'Export as HTML or copy to clipboard.' },
    ],
    screenshots: [{ id: 'ss-1', title: 'Split Editor', description: 'Markdown editor with live HTML preview' }],
    faqs: [{ question: 'Is GitHub Flavored Markdown supported?', answer: 'Yes, GFM including tables, strikethrough, and task lists.' }],
    relatedToolIds: ['tool-11', 'tool-2'],
    rating: 4.8,
    reviewCount: 756,
    usageCount: 187000,
    isNew: false,
    isFeatured: false,
    isTrending: false,
    isPopular: true,
    icon: 'file-code',
    color: '#6366f1',
    gradient: 'linear-gradient(135deg, #6366f1, #8b5cf6)',
    addedDate: '2025-11-08',
  },
  {
    id: 'tool-18',
    name: 'Cron Expression Parser',
    slug: 'cron-parser',
    categoryId: 'cat-1',
    categoryName: 'Developer Tools',
    categoryIcon: 'code-2',
    shortDescription: 'Parse, validate, and describe cron expressions in plain English.',
    description: 'Decode any cron expression into plain English, see the next 10 execution times, and build new cron expressions with a visual builder. Supports standard, quartz, and extended cron syntax.',
    tags: ['Cron', 'Scheduler', 'Linux', 'Parse', 'DevOps'],
    features: ['Plain-English cron description', 'Next 10 execution times', 'Visual cron builder', 'Quartz cron support', 'Timezone-aware execution preview'],
    usageSteps: [
      { step: 1, title: 'Enter Expression', description: 'Paste your cron expression.' },
      { step: 2, title: 'Parse', description: 'Get a plain-English description and next runs.' },
      { step: 3, title: 'Build', description: 'Use the visual builder to craft new expressions.' },
    ],
    screenshots: [{ id: 'ss-1', title: 'Cron Parser', description: 'Cron expression decoder and builder' }],
    faqs: [{ question: 'What cron formats are supported?', answer: 'Standard Unix cron, Quartz (6/7-field), and AWS EventBridge formats.' }],
    relatedToolIds: ['tool-1', 'tool-8'],
    rating: 4.7,
    reviewCount: 291,
    usageCount: 67000,
    isNew: false,
    isFeatured: false,
    isTrending: false,
    isPopular: false,
    icon: 'clock-4',
    color: '#6366f1',
    gradient: 'linear-gradient(135deg, #6366f1, #8b5cf6)',
    addedDate: '2025-12-20',
  },
  {
    id: 'tool-19',
    name: 'Color Palette Generator',
    slug: 'color-palette',
    categoryId: 'cat-8',
    categoryName: 'Generators',
    categoryIcon: 'sparkles',
    shortDescription: 'Generate beautiful color palettes for design systems and UIs.',
    description: 'Generate harmonious color palettes from a base color using color theory algorithms. Export as CSS variables, Tailwind config, or design tokens. Includes accessibility contrast checker.',
    tags: ['Color', 'Palette', 'Design', 'CSS', 'Tailwind', 'Accessibility'],
    features: ['Complementary, analogous, triadic schemes', 'CSS variable export', 'Tailwind config export', 'WCAG contrast ratio checker', 'HEX, RGB, HSL formats', 'Dark/light shade generation'],
    usageSteps: [
      { step: 1, title: 'Pick Base Color', description: 'Enter a hex color or use the color picker.' },
      { step: 2, title: 'Choose Scheme', description: 'Select complementary, analogous, or triadic.' },
      { step: 3, title: 'Export', description: 'Export as CSS, Tailwind, or design tokens.' },
    ],
    screenshots: [{ id: 'ss-1', title: 'Palette View', description: 'Visual color palette grid with export options' }],
    faqs: [{ question: 'Can I check WCAG contrast?', answer: 'Yes, built-in WCAG AA/AAA contrast ratio checker for all palette pairs.' }],
    relatedToolIds: ['tool-9', 'tool-5'],
    rating: 4.9,
    reviewCount: 1024,
    usageCount: 234000,
    isNew: true,
    isFeatured: true,
    isTrending: true,
    isPopular: true,
    icon: 'palette',
    color: '#ec4899',
    gradient: 'linear-gradient(135deg, #ec4899, #8b5cf6)',
    addedDate: '2026-02-01',
  },
  {
    id: 'tool-20',
    name: 'AI Content Analyzer',
    slug: 'ai-content-analyzer',
    categoryId: 'cat-2',
    categoryName: 'AI Tools',
    categoryIcon: 'brain',
    shortDescription: 'Detect AI-generated content and get readability scores instantly.',
    description: 'Analyze any text to detect AI-generated patterns, evaluate readability (Flesch-Kincaid, Gunning Fog), measure originality signals, and get an SEO content quality score.',
    tags: ['AI Detection', 'Readability', 'SEO', 'Content', 'Analysis'],
    features: ['AI-generated content probability score', 'Flesch-Kincaid readability grade', 'Gunning Fog index', 'SEO density analysis', 'Originality signals', 'Sentence complexity breakdown'],
    usageSteps: [
      { step: 1, title: 'Paste Content', description: 'Paste the text you want to analyze.' },
      { step: 2, title: 'Analyze', description: 'Run the multi-metric analysis.' },
      { step: 3, title: 'Review Report', description: 'Review the full content quality report.' },
    ],
    screenshots: [{ id: 'ss-1', title: 'Analysis Dashboard', description: 'Multi-metric content analysis report' }],
    faqs: [{ question: 'How accurate is AI detection?', answer: 'Our model achieves ~87% accuracy on current LLM outputs. Use as a signal, not a verdict.' }],
    relatedToolIds: ['tool-4', 'tool-5', 'tool-11'],
    rating: 4.6,
    reviewCount: 478,
    usageCount: 92000,
    isNew: true,
    isFeatured: false,
    isTrending: true,
    isPopular: false,
    icon: 'scan-text',
    color: '#06b6d4',
    gradient: 'linear-gradient(135deg, #06b6d4, #6366f1)',
    addedDate: '2026-03-10',
  },
];
