-- V19: Simplify User model for Google-only OAuth
DROP TABLE IF EXISTS otps CASCADE;

ALTER TABLE users
    DROP COLUMN IF EXISTS password_hash,
    ALTER COLUMN status SET DEFAULT 'ACTIVE',
    ADD COLUMN IF NOT EXISTS google_id VARCHAR(255) UNIQUE,
    ADD COLUMN IF NOT EXISTS provider VARCHAR(50) DEFAULT 'GOOGLE',
    ADD COLUMN IF NOT EXISTS last_login_at TIMESTAMP WITH TIME ZONE;
